### PR TITLE
Support for sharp-9 and sharp-10 EDOs

### PR DESCRIPTION
**Pull request by Minepig**
Include 10 extra accidentals supported by Musescore, so that the plugin can tune sharp-9 & sharp-10 EDOs.
Note that I completely ignore the original meaning of these accidentals.

### CODE REVIEW

**Comment by euwbah** [comment]
Thanks for this! Do note that while this plugin is still around to keep options open, I'm encouraging everyone to slowly migrate to https://github.com/euwbah/musescore-xen-tuner, especially those seeking more complex tunings (sharp-10+, rank-2/3+, JI, NEJI, ED3, etc...) &mdash; the main benefit of xen tuner being fully customizable accidental support with full reign over tunings and nominals and all other bells and whistles, though, the learning curve is a bit steep.

**Comment by Minepig** [comment]
> Thanks for this! Do note that while this plugin is still around to keep options open, I'm encouraging everyone to slowly migrate to https://github.com/euwbah/musescore-xen-tuner, especially those seeking more complex tunings (sharp-10+, rank-2/3+, JI, NEJI, ED3, etc...) — the main benefit of xen tuner being fully customizable accidental support with full reign over tunings and nominals and all other bells and whistles, though, the learning curve is a bit steep.

thanks, i think the readme should be updated

**Comment by ALLY1950** [comment]
Thanks Minepig and euwbah! Both the plugin update and the new plugin are extremely useful and helpful! Agree with Minepig that we should included the musescore-xen-tuner new project in the MarkDown

**Comment by euwbah** [comment]
Deprecation notice and link to new project is now updated. Just wanted to make sure the new project is working properly and tuning configuration syntax is stabilized before fully deprecating this one. Thanks for contributing here, and feel free to create and share tuning configurations for the new plugin :)

**Pull request merged**
